development:
  adapter: postgresql
  encoding: unicode
  database: reviews_development
  pool: 5
  username: myapp
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: reviews_test
  pool: 5
  username: myapp
  password: password1
